### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by xdsv** [livegrep/livegrep#123]
Is there a Dockerfile for installing livegrep?

Found this one but it's not complete: 
https://github.com/livegrep/livegrep/blob/master/.circleci/Dockerfile

**Comment by tpcwang** [comment]
No, there is not one in this repo. It might be good for livegrep to export a simple docker image as part of the circleci build, but for now, you can pretty easily create a new dockerfile using the circi dockerfile as an example for now. The circleci dockerfile shows you how to set up the build system, you just need to actually build it.

```
... <set up the system to build>
COPY ./ /livegrep/
RUN cd /livegrep && bazel build //...
EXPOSE 9999
WORKDIR /livegrep
ENTRYPOINT ["bazel-bin/src/tools/codesearch", "-listen", "tcp://localhost:9999", "doc/examples/livegrep/index.json"]
```

**Comment by ajbouh** [comment]
I put together a Dockerfile that seems to work, makes a small(ish) image, and doesn't take forever to rebuild.

```dockerfile
# syntax = docker/dockerfile:experimental
FROM ubuntu:16.04 as builder

RUN apt-get update \
  && apt-get -y install \
        gcc-4.8 \
        g++-4.8 \
        libxml2-utils \
        wget \
        pkg-config \
        zip \
        unzip \
        zlib1g-dev \
        openjdk-8-jdk \
        git \
        openssh-client \
        python \
  && rm -rf /var/lib/apt/lists/* \
  && wget --quiet -O /tmp/bazel-0.21.0-installer-linux-x86_64.sh \
    'https://github.com/bazelbuild/bazel/releases/download/0.21.0/bazel-0.21.0-installer-linux-x86_64.sh' \
  && chmod +x /tmp/bazel-*-installer-linux-x86_64.sh \
  && /tmp/bazel-*-installer-linux-x86_64.sh \
  && rm /tmp/bazel-*-installer-linux-x86_64.sh

COPY ./ /livegrep/
RUN --mount=type=cache,target=/root/.cache/bazel \
  cd /livegrep \
  && set -x \
  && bazel build //... \
  && BAZEL_BIN=$(readlink bazel-bin) \
  && rm bazel-bin \
  && cp -R $BAZEL_BIN bazel-bin \
  && BAZEL_EXECROOT=$(readlink bazel-livegrep) \
  && rm bazel-livegrep \
  && cp -R $BAZEL_EXECROOT bazel-livegrep \
  && printf "%s" $BAZEL_EXECROOT > bazel-livegrep.readlink
RUN cd /livegrep \
  && set -x \
  && BAZEL_EXECROOT=$(cat bazel-livegrep.readlink) \
  && mkdir -p $(dirname $BAZEL_EXECROOT) \
  && ln -s $PWD/bazel-livegrep $BAZEL_EXECROOT

FROM ubuntu:16.04 as service
COPY --from=builder /livegrep /livegrep
COPY --from=builder /root/.cache/bazel /root/.cache/bazel

WORKDIR /livegrep
```

To build it, run: `DOCKER_BUILDKIT=1 docker build .`

To run both containers, try: 
`docker run -it --rm --name mylivegrep -p 9999:9999 -p 8910:8910 /livegrep/bazel-bin/src/tools/codesearch -grpc 0.0.0.0:9999 doc/examples/livegrep/index.json`
`docker run -it --rm --network container:mylivegrep 5ff1870b7ea9 /livegrep/bazel-bin/cmd/livegrep/linux_amd64_stripped/livegrep -listen "0.0.0.0:8910"`

This Dockerfile is reasonably fast to rebuild because it shares the bazel cache between builds. (That's what the `--mount=type=cache,target=/root/.cache/bazel` option on RUN does).

Unfortunately this means you need a newer version of docker and you need to use DOCKER_BUILDKIT=1 when running `docker build`

There are two other bits of fanciness in the Dockerfile

1) Compensate for the fact that bazel assumes that the cache directory will be around at runtime (which isn't true in this case as the cache was only mounted for that single RUN). So we copy the parts of the cache that we're going to need into `/livegrep`.
2) Use multi-stage build to avoid emitting all the build dependencies into the final output image. This seems to take the final image from ~2GiB down to ~1GiB. There's probably *a lot* more pruning that can be done (probably don't need all of ubuntu:16.04 or even the entire bazel cache). 

Hope the above is helpful to someone else. Thanks for livegrep, @nelhage!

**Comment by nelhage** [comment]
Neat! I'll take a closer look at that later, but I did want to mention that I also build docker images at https://hub.docker.com/u/livegrep which are based on the Docker files in https://github.com/livegrep/livegrep.com/tree/master/docker and use the build artifacts pushed by the CI in this repository. `livegrep.com` runs off of them using [this docker-compose file](https://github.com/livegrep/livegrep.com/blob/master/compose/docker-compose.yaml) and they should be pretty reusable.

Because they rely on build artifacts from this repository's CI, though, they're not super useful if you want to build your own.

**Comment by ajbouh** [comment]
Got it. They do indeed seem reusable! Thanks for the pointer.
