### ISSUE TITLE
Search filenames

### ISSUE THREAD

**Issue by DanielleSucher** [livegrep/livegrep#17]
Doable now with `. file:FILENAME$`, but it'd be nice if it didn't require the `.` trick (and thus matching on every line of the file).

(I know, I know, just send in a pr. Consider this a reminder to myself to work on it when I have time, unless someone else feels like taking a stab at it first.)

**Comment by gnprice** [comment]
Having run a livegrep instance for the past three years internally at Dropbox, this is probably our top-requested feature :-). Would be great to have!

The way I imagine this working in the UI is something like have a different kind of search results which is just files whose filenames/paths match the query. Those can be really compact to display, because there's no lines or context to show, so just list them first. (Up to some maximum like 10, say. Maybe a bit of UI there to expand to more filename results in place of the file-content results.)

**Comment by jboning** [comment]
I have some code to do this now in a fairly simple way (just regex-searching the filenames). Unfortunately, without indexing it's somewhat slow; simple searches on my corpus of ~290k files take hundreds of milliseconds, compared to tens of milliseconds before the change. So I think we must use an index for this to be a reasonable addition.

**Comment by nelhage** [comment]
`file:<foo> .` doesn't do any particularly clever indexing right now, so I'm a bit confused why a direct search over filenames would be more expensive. Or is it just that you're walking the whole list, instead of bailing after N matches? Can you push the code to a branch somewhere?

**Comment by jboning** [comment]
I was comparing performance to a normal (non-filename) search. When held up to `file:<foo> .`, things look a bit more even. `file:<foo> .` still finishes more quickly for some queries: since every (non-empty) line counts against the result limit, it reaches the limit much earlier. (For example, `file:TODO .` in our corpus hits a 50-match limit in the 4 files. But `TODO` with the modified code ends up checking all 290k filenames, since the corpus contains less than 50 filenames matching TODO.)

I'll push a branch

**Comment by jboning** [comment]
https://github.com/dropbox/livegrep/tree/file-search
