### ISSUE TITLE
Question regarding support for multiple index files

### ISSUE THREAD

**Issue by dgellow** [livegrep/livegrep#398]
Hi there,

I have a question that isn't really an issue, but I don't see a better location to ask: how do you deal with multiple index files? Or is it something that people do not do in practice?

Use case (simplified, in practice I have more than 2 index files):
- I have one index generated by livegrep-github-fetch-reindex that does work pretty well
- But I also have another pretty large set of repos that I need to pre-process locally before they can be indexed — so this one has to be created manually
- As a result I have 2 index fils, each with their own name, config file, and set of local repos
- I understand the indexer is designed to work with a single index and I will have to run 2 instances
- The web frontend also seems to work with a single backend, so I will need 2 instances too

Is my understanding correct than I need N indexer + N web frontend for N index files, or am I missing a simpler way to manage multiple index files?

**Comment by nelhage** [comment]
One option is to use `livegrep-github-fetch-reindex --no-index` to fetch the repos and build the indexer config without actually generating the index, and then stitch that with the config for your other repos into one call to the `codesearch` indexer.

The web frontend does actually support multiple backends, but via a switcher in the UI, rather than merging them, which may not be what you want; see https://livegrep.com and the "linux" vs "ML" toggle.

**Comment by dgellow** [comment]
Thanks Nelson, the dropdown in the web UI is exactly what I was looking for, not sure how I missed it. And I now see [how you define multiple backends](https://github.com/livegrep/livegrep.com/blob/2b5f2aec69ed3037fc8ecb8923e02d48faac7169/compose/conf/livegrep.json#L6).
