### ISSUE TITLE
Built-in file browsing

### ISSUE THREAD

**Issue by gnprice** [livegrep/livegrep#55]
GitHub is pretty OK as a file browser for livegrep search results to link to, but it has a few limitations:
* It's a little slow -- I think of it as quite slow, based on some trials just now it's not bad so maybe it's improved, but it's still not as snappy as livegrep itself;
* Because it's not livegrep, we can't add UI for exploring the codebase with further livegrep searches, cross-references, etc.;
* Some of us have a different, slower backend -- e.g. at Dropbox we use Phabricator, which I think is a decidedly better code-review tool but the [code browsing](https://secure.phabricator.com/source/phabricator/browse/master/src/applications/diffusion/controller/DiffusionBrowseController.php) is not as fast as GitHub let alone livegrep.

This used to be a frequent feature request on our internal instance at Dropbox, and then @christoffer built it :). @jboning plans to send a rebased version of that implementation upstream here soon.

**Comment by tpcwang** [comment]
Cool. We have in-house source browsers that I extended with syntax highlighting. One thing that I do is to link identifier to the ctags backend with ^<term>$. It's a little hacky but it works better than I thought with minimal effort.

It would be kind of nice for the search and browse to be more integrated though. I'd be interested to play around with the rebased version.

**Comment by gnprice** [comment]
Cool!

> One thing that I do is to link identifier to the ctags backend with ^$.

I don't think I understand what you mean here -- can you say more?

**Comment by gnprice** [comment]
Also, if you don't mind saying: I am curious where "we" is for you. :-)

**Comment by tpcwang** [comment]
> I don't think I understand what you mean here -- can you say more?

Sure, we have modified our browser to linkify the identifiers. The link points to our livegrep ctags instance with `^identifier$` as the search term. So if the source browser is showing this snippet:  `def foo: pass`, then the browser will have a link for `foo`, and would link to something like `livegrep/search/ctags?q=^foo$`

> Also, if you don't mind saying: I am curious where "we" is for you. :-)

Not at all. We use livegrep and .NET reference source as our source search tools at National Instruments. We've also looked at DXR in the past - it is an attractive option because it allows for semantic searches, but livegrep is easier to deploy and use for a grab bag of repositories for us, at the moment.
